# @baseUrl = https://ga-winebored.herokuapp.com

# # GET ALL THE WINES
# GET {{baseUrl}}/wines

# ###
# # GET SINGLE WINE 
# GET {{baseUrl}}/wines/5fcd21b1eca2f440bdcec191



@baseUrl = https://akabab.github.io/superhero-api/api/

# GET ALL SUPERHEROES
GET {{baseUrl}}/all.json

###
# GET SINGLE SUPERHERO
GET {{baseUrl}}/id/1.json



